### ISSUE TITLE
3D Datasets

### ISSUE THREAD

**Issue by Michael-Li-Bryant** [provostultrasoundlab/SparseTensorULM#1]
Hi Brice. Thanks for your marvelous work! I wonder if 3D datasets are available for reproducing this work. My sincerest thanks!

**Comment by bricerauby** [comment]
Hi Michael-Li, 
I am happy that you are interested in my work! 
Unfortunately the 3D dataset is around 800GB, so it is difficult to make it available (if you know a solution to share such dataset without cost, I would be happy to do so). You can contact me by email (<first_name>.<last_name>@polymtl.ca) to find a solution so I can transfer it to you.
